// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyuknjwhgadpqhjgiwqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dWtuandoZ2FkcHFoamdpd3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTAwNjksImV4cCI6MjA2NjYyNjA2OX0.sGvwOHlgJKS-la69eC_Scz2tImobP98zKXhpbDA6E4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);